pipeline {
    agent any

    stages {
        stage ('test') {
            steps {
                dir("build_java"){
                    echo "mvn clean compile test"
                }
            }
        }

        stage ('Build application') {
            steps {
                dir("build_java"){
                    bat "mvn -f pom.xml clean install -Dmaven.test.skip=true"
                    bat "tree"
                }
            }
        }

        /*
        stage ('Create docker image') {
            steps {
                echo "creando docker"
            }
        }
        */
    }
}
