pipeline {
    agent any // Se ejecutará en cualquier agente disponible.

    stages {
        stage('Checkout') {
            steps {
                // Realiza la extracción del código desde Git
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('build_java') {
                    echo "Ejecutando pruebas con Maven"
                    bat "mvn clean compile test" // Comando compatible con Windows
                }
            }
        }

        stage('Build application') {
            steps {
                dir('build_java') {
                    echo "Compilando la aplicación"
                    bat "mvn -f pom.xml clean install -Dmaven.test.skip=true" // Comando Maven para Windows
                    bat "tree" // Comando tree para verificar la estructura de directorios
                }
            }
        }

        stage('Create docker image') {
            steps {
                echo "Creando la imagen de Docker"
                // Aquí puedes agregar comandos adicionales para Docker
            }
        }
    }
}
